# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AdInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, vnf_prefix=None):  # noqa: E501
        """AdInfo - a model defined in Swagger

        :param vnf_prefix: The vnf_prefix of this AdInfo.  # noqa: E501
        :type vnf_prefix: str
        """
        self.swagger_types = {
            'vnf_prefix': str
        }

        self.attribute_map = {
            'vnf_prefix': 'vnf_prefix'
        }

        self._vnf_prefix = vnf_prefix

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The adInfo of this AdInfo.  # noqa: E501
        :rtype: AdInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vnf_prefix(self):
        """Gets the vnf_prefix of this AdInfo.


        :return: The vnf_prefix of this AdInfo.
        :rtype: str
        """
        return self._vnf_prefix

    @vnf_prefix.setter
    def vnf_prefix(self, vnf_prefix):
        """Sets the vnf_prefix of this AdInfo.


        :param vnf_prefix: The vnf_prefix of this AdInfo.
        :type vnf_prefix: str
        """

        self._vnf_prefix = vnf_prefix
